projects:
  test:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/parakram/parakramgraphqk.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: rq2xl2wsnzdt7jzlnlhta4ni4e
        codeGenTarget: typescript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-1
      endpoints:
        prod: >-
          https://ge6yezluybamxauqsix2sdpqsa.appsync-api.us-east-1.amazonaws.com/graphql
